appnope==0.1.0
asn1crypto==0.24.0
backcall==0.1.0
bleach==3.1.0
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
cryptography==2.5
cycler==0.10.0
decorator==4.3.2
entrypoints==0.3
Flask==1.0.2
Flask-SQLAlchemy==2.3.2
idna==2.8
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.13.2
Jinja2==2.10
json5==0.6.1
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
kiwisolver==1.0.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mysql-connector-python==8.0.13
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.7.4
numpy==1.15.4
pandas==0.24.1
pandocfilters==1.4.2
parso==0.3.2
pexpect==4.6.0
pickleshare==0.7.5
prometheus-client==0.5.0
prompt-toolkit==2.0.8
protobuf==3.6.0
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.3.1
PyMySQL==0.9.3
pyOpenSSL==19.0.0
pyparsing==2.3.1
PySocks==1.6.8
python-dateutil==2.7.5
pytz==2018.9
pyzmq==17.1.2
requests==2.21.0
scikit-learn==0.20.2
scipy==1.2.0
Send2Trash==1.5.0
simplejson==3.16.0
six==1.12.0
SQLAlchemy==1.2.18
terminado==0.8.1
testpath==0.4.2
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
